# 입력 차원, Batch size, 타임 윈도우, Loss 가중치 등
# cebra_multimodal_pipeline/configs/default_config.yaml

experiment:
  name: "2-afc_decision_making"
  seed: 42

data:
  probe_input_dim: 250
  calcium_input_dim: 150
  time_window: 10
  
training:
  batch_size: 512
  learning_rate: 0.001
  epochs: 100
  temperature: 0.1