dataset:
  drive_base_path: '/content/drive/MyDrive/cebra_data/cache'
  provider: 'churchlandlab'
  target_subjects:
    - 'CSHL045'
  bin_size: 0.025

sampler:
  time_window: 10   # 250ms receptive field (10 * 0.025)
  time_shift: 0

model:
  architecture: 'offset10-model'
  batch_size: 512
  learning_rate: 0.0003
  max_iterations: 2000
  output_dimension: 8
  temperature: 1.0
  distance: 'cosine'